"use client";

import Link from "next/link";
import { ArrowLeft, Send } from "lucide-react";
import { FormEvent, use, useEffect, useState } from "react";

type Ticket = { publicId: string; subject: string; status: string; customerName: string; customerEmail: string; assignedPublicId: string | null; assignedName: string | null; packageCode: string | null; invoiceCode: string | null };
type Message = { body: string; internalOnly: boolean; createdAt: string; authorName: string; isMine: boolean };
type Employee = { publicId: string; fullName: string };
const labels: Record<string, string> = { OPEN: "Abierto", IN_PROGRESS: "En atención", WAITING_CUSTOMER: "Esperando cliente", RESOLVED: "Resuelto", CLOSED: "Cerrado" };
export default function StaffTicketDetailPage({ params }: { params: Promise<{ publicId: string }> }) {
  const { publicId } = use(params); const [ticket, setTicket] = useState<Ticket | null>(null); const [messages, setMessages] = useState<Message[]>([]); const [staff, setStaff] = useState<Employee[]>([]); const [statuses, setStatuses] = useState<string[]>([]); const [status, setStatus] = useState(""); const [assignee, setAssignee] = useState(""); const [message, setMessage] = useState(""); const [internalOnly, setInternalOnly] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function load() { const response = await fetch(`/api/operation/tickets/${publicId}`, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "No se pudo abrir el ticket."); setTicket(payload.ticket as Ticket); setMessages(payload.messages as Message[]); setStaff(payload.staff as Employee[]); setStatuses(payload.statuses as string[]); setStatus(payload.ticket.status); setAssignee(payload.ticket.assignedPublicId || ""); }
  useEffect(() => { let active = true; fetch(`/api/operation/tickets/${publicId}`, { cache: "no-store" }).then(async (r) => { const p = await r.json(); if (!r.ok) throw new Error(p.error || "No se pudo cargar el ticket."); return p; }).then((p) => { if (active) { setTicket(p.ticket as Ticket); setMessages(p.messages as Message[]); setStaff(p.staff as Employee[]); setStatuses(p.statuses as string[]); setStatus(p.ticket.status); setAssignee(p.ticket.assignedPublicId || ""); } }).catch((e) => { if (active) setError(e instanceof Error ? e.message : "No se pudo cargar el ticket."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [publicId]);
  async function updateTicket(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); setNotice(""); try { const response = await fetch(`/api/operation/tickets/${publicId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, assignedToPublicId: assignee || null }) }); const p = await response.json(); if (!response.ok) throw new Error(p.error || "No se pudo actualizar el ticket."); await load(); setNotice("Ticket actualizado."); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo actualizar el ticket."); } finally { setBusy(false); } }
  async function sendReply(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); setNotice(""); try { const response = await fetch(`/api/operation/tickets/${publicId}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message, internalOnly }) }); const p = await response.json(); if (!response.ok) throw new Error(p.error || "No se pudo enviar el mensaje."); setMessage(""); await load(); setNotice(internalOnly ? "Nota interna guardada." : "Respuesta enviada al ticket."); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo enviar el mensaje."); } finally { setBusy(false); } }
  return <section className="operations-support-page"><Link className="back-link" href="/operacion/tickets"><ArrowLeft size={16} /> Volver a tickets</Link>{loading ? <p className="support-empty">Cargando ticket…</p> : error && !ticket ? <p className="form-notice" role="alert">{error}</p> : ticket && <><header className="operations-header"><p className="eyebrow">{ticket.customerName} · {ticket.customerEmail}</p><h1>{ticket.subject}</h1><p className="flow-intro">{ticket.packageCode ? `Paquete ${ticket.packageCode}` : "Solicitud de soporte"}{ticket.invoiceCode ? ` · Factura ${ticket.invoiceCode}` : ""}</p></header>{(error || notice) && <p className={error ? "form-notice" : "staff-success"} role={error ? "alert" : "status"}>{error || notice}</p>}<form className="ticket-admin-controls" onSubmit={updateTicket}><label>Estado<select value={status} onChange={(e) => setStatus(e.target.value)}>{statuses.map((item) => <option key={item} value={item}>{labels[item] || item}</option>)}</select></label><label>Asignar a<select value={assignee} onChange={(e) => setAssignee(e.target.value)}><option value="">Sin asignar</option>{staff.map((person) => <option value={person.publicId} key={person.publicId}>{person.fullName}</option>)}</select></label><button className="form-button" disabled={busy}>Guardar asignación y estado</button></form><div className="ticket-messages staff-ticket-messages">{messages.map((item, index) => <article className={`ticket-message ${item.internalOnly ? "internal" : item.isMine ? "mine" : "staff"}`} key={`${item.createdAt}-${index}`}><small>{item.authorName}{item.internalOnly ? " · Nota interna" : " · Visible para cliente"} · {new Date(item.createdAt).toLocaleString("es-HN")}</small><p>{item.body}</p></article>)}</div>{ticket.status !== "CLOSED" && <form className="ticket-reply-form" onSubmit={sendReply}><label>{internalOnly ? "Nota privada" : "Responder al cliente"}<textarea required minLength={2} maxLength={8000} rows={4} value={message} onChange={(e) => setMessage(e.target.value)} /></label><label className="ticket-internal-toggle"><input type="checkbox" checked={internalOnly} onChange={(e) => setInternalOnly(e.target.checked)} /> Nota interna (no visible al cliente)</label><button className="form-button" disabled={busy}>{busy ? "Guardando…" : internalOnly ? "Guardar nota" : "Enviar respuesta"}<Send size={17} /></button></form>}</>}</section>;
}
