"use client";

import { ChevronRight, Info, Ruler, ScanLine } from "lucide-react";
import { FormEvent, useState } from "react";

export default function ReceiptPage() {
  const [step, setStep] = useState(1);
  function nextStep(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setStep((current) => Math.min(current + 1, 3)); }
  return <section className="receipt-page"><p className="eyebrow">Recepcion Miami</p><h1>Ingresar paquete</h1><p className="flow-intro">Flujo de interfaz. La recepción se habilitará cuando se conecte el inicio de sesión y el servicio operativo.</p><ol className="receipt-steps"><li className={step >= 1 ? "active" : ""}>Escanear</li><li className={step >= 2 ? "active" : ""}>Medir</li><li className={step >= 3 ? "active" : ""}>Ubicar</li></ol>{step === 1 && <form className="keygo-form" onSubmit={nextStep}><label>Tracking recibido <span className="input-with-icon"><ScanLine size={20} /><input required autoFocus placeholder="Escanea o escribe el tracking" /></span></label><aside className="info-box"><Info size={19} /><span>La identificación de cliente se validará en el servidor antes de continuar.</span></aside><button className="form-button">Confirmar identificacion <ChevronRight size={18} /></button></form>}{step === 2 && <form className="keygo-form" onSubmit={nextStep}><label>Peso (kg)<input required type="number" min="0.001" step="0.001" placeholder="0.000" /></label><div className="field-row"><label>Largo (cm)<input required type="number" min="0.01" /></label><label>Ancho (cm)<input required type="number" min="0.01" /></label></div><label>Alto (cm)<input required type="number" min="0.01" /></label><button className="form-button">Guardar medidas <Ruler size={18} /></button></form>}{step === 3 && <form className="keygo-form"><label>Ubicacion en bodega<select defaultValue=""><option value="" disabled>Selecciona una ubicacion</option><option>MIA-A-03-12 · Estante A, nivel 3</option></select></label><aside className="info-box"><Info size={19} /><span>La confirmación queda bloqueada hasta que el backend valide el permiso, la ubicación y que el paquete no haya sido recibido.</span></aside><button className="form-button" disabled>Confirmar recepcion</button></form>}</section>;
}